const STORAGE_KEY="tsf-partnerverwaltung-v1";
const navItems=[{id:"uebersicht",label:"Übersicht",icon:"▦"},{id:"firmenfitness",label:"Firmenfitness",icon:"▤"},{id:"vereinsfitness",label:"Vereinsfitness",icon:"▥"},{id:"verwaltung",label:"Verwaltung",icon:"▧"}];
const seedPartners=[
{id:"p-1001",type:"firma",name:"Bosch GmbH",contactName:"Mara Schneider",contactPhone:"+49 711 811-4200",contactEmail:"mara.schneider@bosch.com",studio:"Echterdingen",closedBy:"Clubleitung Echterdingen",lastContact:"2026-06-12",conditions:"Firmenfitness 1 Monat 39 EUR, keine Startgebühr bei Mitarbeiterausweis.",notes:"Nachweis über Bosch Mitarbeiterausweis oder digitale Beschäftigungsbestätigung erforderlich.",status:"aktiv"},
{id:"p-1002",type:"firma",name:"Daimler Truck AG",contactName:"Thomas Keller",contactPhone:"+49 711 8485-233",contactEmail:"fitness@daimlertruck.com",studio:"Leinfelden",closedBy:"Regionalleitung",lastContact:"2026-05-28",conditions:"Firmenfitness Premium 12 Monate, 15 % Rabatt, Startpaket inklusive.",notes:"Quartalsweise Auswertung der aktiven Mitgliedschaften an HR senden.",status:"aktiv"},
{id:"p-1003",type:"firma",name:"Festo SE & Co. KG",contactName:"Julia Berger",contactPhone:"+49 711 347-0",contactEmail:"j.berger@festo.com",studio:"Nürtingen",closedBy:"Studioleitung Nürtingen",lastContact:"2026-04-18",conditions:"Firmenfitness Classic, 8 % Rabatt, Probemonat nach HR-Freigabe.",notes:"Kooperation soll im Juli 2026 neu bewertet werden.",status:"offen"},
{id:"p-1004",type:"verein",name:"VfL Pfullingen",contactName:"Sven Maier",contactPhone:"+49 7121 78033",contactEmail:"geschaeftsstelle@vfl-pfullingen.de",studio:"Reutlingen",closedBy:"Clubleitung Reutlingen",lastContact:"2026-06-03",conditions:"Vereinsfitness 12 % Rabatt, Team-Screening nach Terminvereinbarung.",notes:"Gilt für Mitglieder mit aktueller Vereinsbestätigung. Mannschaftsaktionen separat abstimmen.",status:"aktiv"},
{id:"p-1005",type:"verein",name:"TSV Leinfelden",contactName:"Nadine Roth",contactPhone:"+49 711 754240",contactEmail:"info@tsv-leinfelden.de",studio:"Leinfelden",closedBy:"Studioleitung Leinfelden",lastContact:"2026-03-21",conditions:"Vereinsfitness 10 % auf Laufzeitverträge, keine Aufnahmegebühr bei Vereinsnachweis.",notes:"Jugendliche nur mit regulärer Einverständniserklärung und Beratungstermin.",status:"aktiv"},
{id:"p-1006",type:"verein",name:"SV Salamander Kornwestheim",contactName:"Patrick Braun",contactPhone:"+49 7154 20245",contactEmail:"partner@svkornwestheim.de",studio:"Kornwestheim",closedBy:"Clubleitung Kornwestheim",lastContact:"2026-02-15",conditions:"Vereinskondition offen, Bestandstarif bis Neuverhandlung gültig.",notes:"Ansprechpartner wechselt im Sommer. Vertrag vor Verlängerung prüfen.",status:"kritisch"}
];
const state={page:"uebersicht",role:"employee",filter:"alle",studio:"alle",query:"",partners:loadPartners()};
const $=s=>document.querySelector(s);
const els={desktopNav:$("#desktopNav"),mobileNav:$("#mobileNav"),breadcrumbPage:$("#breadcrumbPage"),currentRoleLabel:$("#currentRoleLabel"),roleToggle:$("#roleToggle"),globalSearch:$("#globalSearch"),pageEyebrow:$("#pageEyebrow"),pageTitle:$("#pageTitle"),pageDescription:$("#pageDescription"),pagePrimaryAction:$("#pagePrimaryAction"),kpiGrid:$("#kpiGrid"),partnerSearch:$("#partnerSearch"),studioFilter:$("#studioFilter"),overviewSections:$("#overviewSections"),taskList:$("#taskList"),partnerTableBody:$("#partnerTableBody"),partnerMobileList:$("#partnerMobileList"),resultCount:$("#resultCount"),resetFilters:$("#resetFilters"),emptyReset:$("#emptyReset"),emptyState:$("#emptyState"),adminPanel:$("#adminPanel"),partnerForm:$("#partnerForm"),formError:$("#formError"),cancelEdit:$("#cancelEdit"),detailBackdrop:$("#detailBackdrop"),detailDrawer:$("#detailDrawer"),drawerType:$("#drawerType"),drawerTitle:$("#drawerTitle"),drawerBody:$("#drawerBody"),closeDrawer:$("#closeDrawer"),toast:$("#toast")};
function isAdmin(){return state.role==="admin"}
function loadPartners(){try{const raw=localStorage.getItem(STORAGE_KEY);return raw?JSON.parse(raw):seedPartners}catch{return seedPartners}}
function savePartners(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state.partners))}
function formatDate(value){return new Intl.DateTimeFormat("de-DE",{day:"2-digit",month:"2-digit",year:"numeric"}).format(new Date(`${value}T12:00:00`))}
function typeLabel(type){return type==="firma"?"Firmenfitness":"Vereinsfitness"}
function statusBadge(status){const map={aktiv:["badge-active","Aktiv"],offen:["badge-open","Prüfen"],kritisch:["badge-critical","Kritisch"]};const [cls,label]=map[status]||["badge-neutral","Neutral"];return `<span class="badge ${cls}">${label}</span>`}
function truncate(text,len){return text.length>len?`${text.slice(0,len-1)}…`:text}
function renderNavigation(){const html=navItems.map(item=>`<button class="nav-item ${state.page===item.id?"is-active":""}" type="button" data-page="${item.id}"><span aria-hidden="true">${item.icon}</span><span>${item.label}</span></button>`).join("");els.desktopNav.innerHTML=html;els.mobileNav.innerHTML=html;document.querySelectorAll("[data-page]").forEach(btn=>btn.addEventListener("click",()=>setPage(btn.dataset.page)))}
function setPage(page){state.page=page;if(page==="firmenfitness")state.filter="firma";if(page==="vereinsfitness")state.filter="verein";if(page==="uebersicht")state.filter="alle";if(page==="verwaltung"){state.filter="alle";state.role="admin"}render()}
function filteredPartners(){const q=state.query.trim().toLowerCase();return state.partners.filter(p=>{const byType=state.filter==="alle"||p.type===state.filter;const byStudio=state.studio==="alle"||p.studio===state.studio;const publicText=[p.name,typeLabel(p.type),p.conditions].join(" ").toLowerCase();const adminText=[p.name,typeLabel(p.type),p.conditions,p.contactName,p.contactEmail,p.contactPhone,p.notes,p.closedBy,p.studio].join(" ").toLowerCase();return byType&&byStudio&&(!q||(isAdmin()?adminText:publicText).includes(q))})}
function renderHeader(){const configs={uebersicht:["Partnerdatenbank","Kooperationspartner im Überblick",isAdmin()?"Suche Partner, prüfe Konditionen und verwalte interne Ansprechpartner.":"Suche Firmen- und Vereinsfitnesspartner und prüfe die hinterlegten Konditionen.","Partner anlegen"],firmenfitness:["Firmenfitness","Firmenpartner suchen",isAdmin()?"Alle Firmenkooperationen inklusive Kontakt, Konditionen und internen Hinweisen.":"Alle Firmenkooperationen mit den freigegebenen Konditionen für Mitarbeiter.","Firmenpartner anlegen"],vereinsfitness:["Vereinsfitness","Vereinspartner suchen",isAdmin()?"Vereine, Konditionen, Ansprechpartner und interne Nachweisregeln.":"Alle Vereinspartner mit den freigegebenen Konditionen für Mitarbeiter.","Vereinspartner anlegen"],verwaltung:["Verwaltung","Partnerdaten pflegen","Clubleiter legen Kooperationen an, aktualisieren Konditionen und entfernen veraltete Einträge.","Partner speichern"]};const c=configs[state.page];els.pageEyebrow.textContent=c[0];els.pageTitle.textContent=c[1];els.pageDescription.textContent=c[2];els.pagePrimaryAction.textContent=`+ ${c[3]}`;els.breadcrumbPage.textContent=navItems.find(n=>n.id===state.page).label;els.currentRoleLabel.textContent=isAdmin()?"Clubleiter":"Mitarbeiter";els.roleToggle.textContent=isAdmin()?"Lesemodus":"Admin-Modus";els.pagePrimaryAction.hidden=!isAdmin()&&state.page!=="verwaltung";document.body.dataset.role=state.role}
function renderKpis(){const firms=state.partners.filter(p=>p.type==="firma").length;const clubs=state.partners.filter(p=>p.type==="verein").length;const open=state.partners.filter(p=>p.status!=="aktiv").length;const recent=state.partners.filter(p=>p.lastContact>="2026-06-01").length;const items=isAdmin()?[["Firmenpartner",firms,"aktive und offene Firmenkooperationen"],["Vereinspartner",clubs,"Vereine mit hinterlegter Kondition"],["Zu prüfen",open,"Einträge mit offenem Status"],["Kontakt im Juni",recent,"aktualisierte Kooperationen"]]:[["Firmenpartner",firms,"Partner mit freigegebenen Konditionen"],["Vereinspartner",clubs,"Vereine mit freigegebenen Konditionen"],["Konditionen",firms+clubs,"durchsuchbare Partnervereinbarungen"],["Ansicht","Nur Tarife","Kontakte nur für Clubleiter sichtbar"]];els.kpiGrid.innerHTML=items.map(k=>`<article class="card kpi-card"><span>${k[0]}</span><strong>${k[1]}</strong><p>${k[2]}</p></article>`).join("")}
function renderTasks(){if(els.taskList)els.taskList.innerHTML=""}
function renderTableHeader(){const admin=isAdmin()?"<th>Ansprechpartner</th><th>Letzter Kontakt</th><th>Status</th>":"";return `<tr><th>Partner</th><th>Art</th><th>Konditionen</th>${admin}<th>Aktion</th></tr>`}
function renderList(){const partners=filteredPartners();els.resultCount.textContent=partners.length===1?"1 Eintrag":`${partners.length} Einträge`;els.emptyState.hidden=partners.length>0;document.querySelector("thead").innerHTML=renderTableHeader();els.partnerTableBody.innerHTML=partners.map(renderTableRow).join("");els.partnerMobileList.innerHTML=partners.map(renderMobileCard).join("");document.querySelectorAll("[data-view]").forEach(b=>b.addEventListener("click",()=>openDrawer(b.dataset.view)));document.querySelectorAll("[data-edit]").forEach(b=>b.addEventListener("click",()=>editPartner(b.dataset.edit)));document.querySelectorAll("[data-delete]").forEach(b=>b.addEventListener("click",()=>deletePartner(b.dataset.delete)))}
function renderTableRow(p){const admin=isAdmin()?`<td><div class="partner-name"><strong>${p.contactName}</strong><span>${p.contactEmail}</span></div></td><td>${formatDate(p.lastContact)}</td><td>${statusBadge(p.status)}</td>`:"";return `<tr><td><div class="partner-name"><strong>${p.name}</strong><span>${isAdmin()?p.studio:typeLabel(p.type)}</span></div></td><td>${typeLabel(p.type)}</td><td>${truncate(p.conditions,74)}</td>${admin}<td><div class="row-actions"><button class="icon-btn" type="button" data-view="${p.id}" aria-label="${p.name} öffnen">↗</button>${adminActions(p)}</div></td></tr>`}
function renderMobileCard(p){const adminMeta=isAdmin()?`<span>${p.contactName} · ${p.contactPhone}</span><span>Letzter Kontakt: ${formatDate(p.lastContact)}</span>`:"";return `<article class="mobile-card"><div class="mobile-card-top"><div class="partner-name"><strong>${p.name}</strong><span>${typeLabel(p.type)}${isAdmin()?` · ${p.studio}`:""}</span></div>${isAdmin()?statusBadge(p.status):""}</div><div class="mobile-meta"><span>${truncate(p.conditions,110)}</span>${adminMeta}</div><div class="mobile-actions"><button class="btn btn-secondary" type="button" data-view="${p.id}">Öffnen</button>${isAdmin()?`<button class="btn btn-danger" type="button" data-delete="${p.id}">Löschen</button>`:""}</div></article>`}
function adminActions(p){return isAdmin()?`<button class="icon-btn" type="button" data-edit="${p.id}" aria-label="${p.name} bearbeiten">✎</button><button class="icon-btn btn-danger" type="button" data-delete="${p.id}" aria-label="${p.name} löschen">×</button>`:""}
function openDrawer(id){const p=state.partners.find(item=>item.id===id);if(!p)return;els.drawerType.textContent=typeLabel(p.type);els.drawerTitle.textContent=p.name;const adminSections=isAdmin()?`<div class="detail-section"><span>Status</span><strong>${statusBadge(p.status)}</strong></div><div class="detail-section"><span>Ansprechpartner</span><strong>${p.contactName}</strong><p>${p.contactPhone}</p><p>${p.contactEmail}</p></div><div class="detail-section"><span>Besonderheiten</span><p>${p.notes||"Keine Besonderheiten hinterlegt."}</p></div><div class="detail-section"><span>Kooperation</span><p>Geschlossen von: ${p.closedBy}</p><p>Zuständiges Studio: ${p.studio}</p><p>Letzter Kontakt: ${formatDate(p.lastContact)}</p></div><button class="btn btn-secondary" type="button" data-edit="${p.id}">Bearbeiten</button>`:"";els.drawerBody.innerHTML=`<div class="detail-section"><span>Konditionen</span><p>${p.conditions}</p></div>${adminSections}`;els.detailBackdrop.hidden=false;els.detailDrawer.classList.add("is-open");els.detailDrawer.setAttribute("aria-hidden","false");els.closeDrawer.focus();els.drawerBody.querySelectorAll("[data-edit]").forEach(b=>b.addEventListener("click",()=>editPartner(b.dataset.edit)))}
function closeDrawer(){els.detailDrawer.classList.remove("is-open");els.detailDrawer.setAttribute("aria-hidden","true");setTimeout(()=>{if(!els.detailDrawer.classList.contains("is-open"))els.detailBackdrop.hidden=true},220)}
function editPartner(id){const p=state.partners.find(item=>item.id===id);if(!p)return;state.role="admin";state.page="verwaltung";closeDrawer();["partnerId","partnerType","partnerName","contactName","contactPhone","contactEmail","partnerStudio","closedBy","lastContact","conditions","notes"].forEach(key=>{const map={partnerId:p.id,partnerType:p.type,partnerName:p.name,contactName:p.contactName,contactPhone:p.contactPhone,contactEmail:p.contactEmail,partnerStudio:p.studio,closedBy:p.closedBy,lastContact:p.lastContact,conditions:p.conditions,notes:p.notes};$(`#${key}`).value=map[key]});render();els.adminPanel.scrollIntoView({behavior:"smooth",block:"start"})}
function deletePartner(id){const p=state.partners.find(item=>item.id===id);if(!p||!confirm(`${p.name} wirklich löschen? Diese Aktion entfernt den lokalen Eintrag.`))return;state.partners=state.partners.filter(item=>item.id!==id);savePartners();render();showToast(`${p.name} wurde gelöscht.`)}
function handleFormSubmit(e){e.preventDefault();if(!isAdmin()){showToast("Nur Clubleiter können Partnerdaten speichern.","error");return}if(!els.partnerForm.checkValidity()){els.formError.hidden=false;els.partnerForm.reportValidity();return}els.formError.hidden=true;const id=$("#partnerId").value||`p-${Date.now()}`;const partner={id,type:$("#partnerType").value,name:$("#partnerName").value.trim(),contactName:$("#contactName").value.trim(),contactPhone:$("#contactPhone").value.trim(),contactEmail:$("#contactEmail").value.trim(),studio:$("#partnerStudio").value,closedBy:$("#closedBy").value.trim(),lastContact:$("#lastContact").value,conditions:$("#conditions").value.trim(),notes:$("#notes").value.trim(),status:"aktiv"};const i=state.partners.findIndex(p=>p.id===id);if(i>=0){state.partners[i]=partner;showToast(`${partner.name} wurde aktualisiert.`)}else{state.partners.unshift(partner);showToast(`${partner.name} wurde angelegt.`)}savePartners();resetForm();render()}
function resetForm(){els.partnerForm.reset();$("#partnerId").value="";$("#lastContact").value=new Date().toISOString().slice(0,10);els.formError.hidden=true}
function showToast(message,type="success"){els.toast.textContent=message;els.toast.style.borderLeftColor=type==="error"?"var(--error)":"var(--success)";els.toast.hidden=false;clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>els.toast.hidden=true,3600)}
function resetFilters(){state.query="";state.filter=state.page==="firmenfitness"?"firma":state.page==="vereinsfitness"?"verein":"alle";state.studio="alle";render()}
function renderAdminVisibility(){const adminPage=state.page==="verwaltung";els.adminPanel.hidden=!adminPage;els.overviewSections.hidden=adminPage;els.partnerForm.querySelectorAll("input,select,textarea,button").forEach(field=>field.disabled=!isAdmin())}
function syncInputs(){els.partnerSearch.value=state.query;els.globalSearch.value=state.query;els.studioFilter.value=state.studio;document.querySelectorAll(".chip").forEach(c=>c.classList.toggle("is-active",c.dataset.filter===state.filter))}
function render(){renderHeader();renderNavigation();renderKpis();renderTasks();renderAdminVisibility();renderList();syncInputs()}
function bindEvents(){els.roleToggle.addEventListener("click",()=>{state.role=isAdmin()?"employee":"admin";if(state.role==="employee"&&state.page==="verwaltung")state.page="uebersicht";render()});els.pagePrimaryAction.addEventListener("click",()=>{state.role="admin";state.page="verwaltung";render();els.adminPanel.scrollIntoView({behavior:"smooth"})});[els.partnerSearch,els.globalSearch].forEach(input=>input.addEventListener("input",e=>{state.query=e.target.value;syncInputs();renderList()}));document.querySelectorAll(".chip").forEach(chip=>chip.addEventListener("click",()=>{state.filter=chip.dataset.filter;if(state.filter==="firma")state.page="firmenfitness";if(state.filter==="verein")state.page="vereinsfitness";if(state.filter==="alle"&&state.page!=="verwaltung")state.page="uebersicht";render()}));els.studioFilter.addEventListener("change",e=>{state.studio=e.target.value;renderList()});els.resetFilters.addEventListener("click",resetFilters);els.emptyReset.addEventListener("click",resetFilters);els.partnerForm.addEventListener("submit",handleFormSubmit);els.cancelEdit.addEventListener("click",resetForm);els.closeDrawer.addEventListener("click",closeDrawer);els.detailBackdrop.addEventListener("click",closeDrawer);document.querySelectorAll("[data-quick]").forEach(btn=>btn.addEventListener("click",()=>setPage(btn.dataset.quick==="firma"?"firmenfitness":btn.dataset.quick==="verein"?"vereinsfitness":"verwaltung")));document.addEventListener("keydown",e=>{if(e.key==="Escape")closeDrawer()})}
bindEvents();resetForm();render();
