const STORAGE_KEY="tsf-partnerverwaltung-v2";
const pageByFile={"":"uebersicht","index.html":"uebersicht","firmenfitness.html":"firmenfitness","vereinsfitness.html":"vereinsfitness","verwaltung.html":"verwaltung"};
const navItems=[{id:"uebersicht",label:"Übersicht",href:"index.html",icon:"▦"},{id:"firmenfitness",label:"Firmenfitness",href:"firmenfitness.html",icon:"▤"},{id:"vereinsfitness",label:"Vereinsfitness",href:"vereinsfitness.html",icon:"▥"},{id:"verwaltung",label:"Verwaltung",href:"verwaltung.html",icon:"▧"}];
const seedPartners=[{id:"p-1001",type:"firma",name:"Bosch GmbH",contactName:"Mara Schneider",contactPhone:"+49 711 811-4200",contactEmail:"mara.schneider@bosch.com",studio:"Echterdingen",closedBy:"Clubleitung Echterdingen",lastContact:"2026-06-12",conditions:"Firmenfitness 1 Monat 39 EUR, keine Startgebühr bei Mitarbeiterausweis.",notes:"Nachweis über Bosch Mitarbeiterausweis oder digitale Beschäftigungsbestätigung erforderlich.",status:"aktiv"},{id:"p-1002",type:"firma",name:"Daimler Truck AG",contactName:"Thomas Keller",contactPhone:"+49 711 8485-233",contactEmail:"fitness@daimlertruck.com",studio:"Leinfelden",closedBy:"Regionalleitung",lastContact:"2026-05-28",conditions:"Firmenfitness Premium 12 Monate, 15 % Rabatt, Startpaket inklusive.",notes:"Quartalsweise Auswertung der aktiven Mitgliedschaften an HR senden.",status:"aktiv"},{id:"p-1003",type:"firma",name:"Festo SE & Co. KG",contactName:"Julia Berger",contactPhone:"+49 711 347-0",contactEmail:"j.berger@festo.com",studio:"Nürtingen",closedBy:"Studioleitung Nürtingen",lastContact:"2026-04-18",conditions:"Firmenfitness Classic, 8 % Rabatt, Probemonat nach HR-Freigabe.",notes:"Kooperation soll im Juli 2026 neu bewertet werden.",status:"offen"},{id:"p-1004",type:"verein",name:"VfL Pfullingen",contactName:"Sven Maier",contactPhone:"+49 7121 78033",contactEmail:"geschaeftsstelle@vfl-pfullingen.de",studio:"Reutlingen",closedBy:"Clubleitung Reutlingen",lastContact:"2026-06-03",conditions:"Vereinsfitness 12 % Rabatt, Team-Screening nach Terminvereinbarung.",notes:"Gilt für Mitglieder mit aktueller Vereinsbestätigung. Mannschaftsaktionen separat abstimmen.",status:"aktiv"},{id:"p-1005",type:"verein",name:"TSV Leinfelden",contactName:"Nadine Roth",contactPhone:"+49 711 754240",contactEmail:"info@tsv-leinfelden.de",studio:"Leinfelden",closedBy:"Studioleitung Leinfelden",lastContact:"2026-03-21",conditions:"Vereinsfitness 10 % auf Laufzeitverträge, keine Aufnahmegebühr bei Vereinsnachweis.",notes:"Jugendliche nur mit regulärer Einverständniserklärung und Beratungstermin.",status:"aktiv"},{id:"p-1006",type:"verein",name:"SV Salamander Kornwestheim",contactName:"Patrick Braun",contactPhone:"+49 7154 20245",contactEmail:"partner@svkornwestheim.de",studio:"Kornwestheim",closedBy:"Clubleitung Kornwestheim",lastContact:"2026-02-15",conditions:"Vereinskondition offen, Bestandstarif bis Neuverhandlung gültig.",notes:"Ansprechpartner wechselt im Sommer. Vertrag vor Verlängerung prüfen.",status:"kritisch"}];
const file=location.pathname.split("/").pop();
const state={page:pageByFile[file]||"uebersicht",role:localStorage.getItem("tsf-role")||"employee",query:"",studio:"alle",partners:loadPartners()};
const $=s=>document.querySelector(s);
const els={desktopNav:$("#desktopNav"),mobileNav:$("#mobileNav"),breadcrumbPage:$("#breadcrumbPage"),currentRoleLabel:$("#currentRoleLabel"),roleToggle:$("#roleToggle"),globalSearch:$("#globalSearch"),pageEyebrow:$("#pageEyebrow"),pageTitle:$("#pageTitle"),pageDescription:$("#pageDescription"),pagePrimaryAction:$("#pagePrimaryAction"),kpiGrid:$("#kpiGrid"),partnerSearch:$("#partnerSearch"),studioFilter:$("#studioFilter"),overviewSections:$("#overviewSections"),partnerTableBody:$("#partnerTableBody"),partnerMobileList:$("#partnerMobileList"),resultCount:$("#resultCount"),resetFilters:$("#resetFilters"),emptyReset:$("#emptyReset"),emptyState:$("#emptyState"),adminPanel:$("#adminPanel"),partnerForm:$("#partnerForm"),formError:$("#formError"),cancelEdit:$("#cancelEdit"),detailBackdrop:$("#detailBackdrop"),detailDrawer:$("#detailDrawer"),drawerType:$("#drawerType"),drawerTitle:$("#drawerTitle"),drawerBody:$("#drawerBody"),closeDrawer:$("#closeDrawer"),toast:$("#toast")};
function isAdmin(){return state.role==="admin"}
function loadPartners(){try{const raw=localStorage.getItem(STORAGE_KEY);return raw?JSON.parse(raw):seedPartners}catch{return seedPartners}}
function savePartners(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state.partners))}
function typeLabel(t){return t==="firma"?"Firmenfitness":"Vereinsfitness"}
function formatDate(v){return new Intl.DateTimeFormat("de-DE",{day:"2-digit",month:"2-digit",year:"numeric"}).format(new Date(`${v}T12:00:00`))}
function statusBadge(s){const m={aktiv:["badge-active","Aktiv"],offen:["badge-open","Prüfen"],kritisch:["badge-critical","Kritisch"]};const [c,l]=m[s]||["badge-neutral","Neutral"];return `<span class="badge ${c}">${l}</span>`}
function pageType(){return state.page==="firmenfitness"?"firma":state.page==="vereinsfitness"?"verein":"alle"}
function filteredPartners(){const type=pageType(),q=state.query.trim().toLowerCase();return state.partners.filter(p=>{const typeOk=type==="alle"||p.type===type,studioOk=state.studio==="alle"||p.studio===state.studio;const pub=[p.name,typeLabel(p.type),p.conditions].join(" ").toLowerCase();const adm=[p.name,typeLabel(p.type),p.conditions,p.contactName,p.contactEmail,p.contactPhone,p.notes,p.closedBy,p.studio].join(" ").toLowerCase();return typeOk&&studioOk&&(!q||(isAdmin()?adm:pub).includes(q))})}
function renderNavigation(){const html=navItems.map(i=>`<a class="nav-item ${state.page===i.id?"is-active":""}" href="${i.href}"><span aria-hidden="true">${i.icon}</span><span>${i.label}</span></a>`).join("");els.desktopNav.innerHTML=html;els.mobileNav.innerHTML=html}
function renderHeader(){const cfg={uebersicht:["Partnerdatenbank","Kooperationspartner im Überblick","Suche nach Firmen und Vereinen und prüfe die freigegebenen Konditionen."],firmenfitness:["Firmenfitness","Firmenpartner","Alle Firmenkooperationen mit den freigegebenen Konditionen."],vereinsfitness:["Vereinsfitness","Vereinspartner","Alle Vereinspartner mit den freigegebenen Konditionen."],verwaltung:["Verwaltung","Partner verwalten","Kooperationen anlegen, bearbeiten und löschen."]}[state.page];els.pageEyebrow.textContent=cfg[0];els.pageTitle.textContent=cfg[1];els.pageDescription.textContent=cfg[2];els.breadcrumbPage.textContent=navItems.find(i=>i.id===state.page).label;els.currentRoleLabel.textContent=isAdmin()?"Clubleiter":"Mitarbeiter";els.roleToggle.textContent=isAdmin()?"Lesemodus":"Admin-Modus";els.pagePrimaryAction.hidden=!isAdmin()||state.page!=="verwaltung";els.pagePrimaryAction.textContent="+ Partner speichern";document.body.dataset.page=state.page;document.body.dataset.role=state.role}
function renderKpis(){const firms=state.partners.filter(p=>p.type==="firma").length,clubs=state.partners.filter(p=>p.type==="verein").length,visible=filteredPartners().length;const items=[["Firmenpartner",firms,"freigegebene Konditionen"],["Vereinspartner",clubs,"freigegebene Konditionen"],["Aktuelle Seite",visible,"sichtbare Einträge"],["Ansicht",isAdmin()?"Intern":"Tarife",isAdmin()?"mit Kontakten":"ohne Kontakte"]];els.kpiGrid.innerHTML=items.map(k=>`<article class="card kpi-card"><span>${k[0]}</span><strong>${k[1]}</strong><p>${k[2]}</p></article>`).join("")}
function renderTableHeader(){const admin=isAdmin()?"<th>Ansprechpartner</th><th>Letzter Kontakt</th><th>Status</th>":"";return `<tr><th>Partner</th><th>Art</th><th>Konditionen</th>${admin}<th>Aktion</th></tr>`}
function renderList(){const ps=filteredPartners();els.resultCount.textContent=ps.length===1?"1 Eintrag":`${ps.length} Einträge`;els.emptyState.hidden=ps.length>0;document.querySelector("thead").innerHTML=renderTableHeader();els.partnerTableBody.innerHTML=ps.map(renderTableRow).join("");els.partnerMobileList.innerHTML=ps.map(renderMobileCard).join("");document.querySelectorAll("[data-view]").forEach(b=>b.addEventListener("click",()=>openDrawer(b.dataset.view)));document.querySelectorAll("[data-edit]").forEach(b=>b.addEventListener("click",()=>editPartner(b.dataset.edit)));document.querySelectorAll("[data-delete]").forEach(b=>b.addEventListener("click",()=>deletePartner(b.dataset.delete)))}
function renderTableRow(p){const admin=isAdmin()?`<td><div class="partner-name"><strong>${p.contactName}</strong><span>${p.contactEmail}</span></div></td><td>${formatDate(p.lastContact)}</td><td>${statusBadge(p.status)}</td>`:"";return `<tr><td><div class="partner-name"><strong>${p.name}</strong><span>${isAdmin()?p.studio:typeLabel(p.type)}</span></div></td><td>${typeLabel(p.type)}</td><td>${p.conditions}</td>${admin}<td><div class="row-actions"><button class="icon-btn" type="button" data-view="${p.id}" aria-label="${p.name} öffnen">↗</button>${adminActions(p)}</div></td></tr>`}
function renderMobileCard(p){const admin=isAdmin()?`<span>${p.contactName} · ${p.contactPhone}</span><span>Letzter Kontakt: ${formatDate(p.lastContact)}</span>`:"";return `<article class="mobile-card"><div class="mobile-card-top"><div class="partner-name"><strong>${p.name}</strong><span>${typeLabel(p.type)}${isAdmin()?` · ${p.studio}`:""}</span></div>${isAdmin()?statusBadge(p.status):""}</div><div class="mobile-meta"><span>${p.conditions}</span>${admin}</div><div class="mobile-actions"><button class="btn btn-secondary" type="button" data-view="${p.id}">Öffnen</button>${isAdmin()?`<button class="btn btn-danger" type="button" data-delete="${p.id}">Löschen</button>`:""}</div></article>`}
function adminActions(p){return isAdmin()?`<button class="icon-btn" type="button" data-edit="${p.id}" aria-label="${p.name} bearbeiten">✎</button><button class="icon-btn btn-danger" type="button" data-delete="${p.id}" aria-label="${p.name} löschen">×</button>`:""}
function openDrawer(id){const p=state.partners.find(x=>x.id===id);if(!p)return;const admin=isAdmin()?`<div class="detail-section"><span>Ansprechpartner</span><strong>${p.contactName}</strong><p>${p.contactPhone}</p><p>${p.contactEmail}</p></div><div class="detail-section"><span>Besonderheiten</span><p>${p.notes||"Keine Besonderheiten hinterlegt."}</p></div><div class="detail-section"><span>Kooperation</span><p>Geschlossen von: ${p.closedBy}</p><p>Zuständiges Studio: ${p.studio}</p><p>Letzter Kontakt: ${formatDate(p.lastContact)}</p></div><button class="btn btn-secondary" type="button" data-edit="${p.id}">Bearbeiten</button>`:"";els.drawerType.textContent=typeLabel(p.type);els.drawerTitle.textContent=p.name;els.drawerBody.innerHTML=`<div class="detail-section"><span>Konditionen</span><p>${p.conditions}</p></div>${admin}`;els.detailBackdrop.hidden=false;els.detailDrawer.classList.add("is-open");els.detailDrawer.setAttribute("aria-hidden","false");els.closeDrawer.focus();els.drawerBody.querySelectorAll("[data-edit]").forEach(b=>b.addEventListener("click",()=>editPartner(b.dataset.edit)))}
function closeDrawer(){els.detailDrawer.classList.remove("is-open");els.detailDrawer.setAttribute("aria-hidden","true");setTimeout(()=>{if(!els.detailDrawer.classList.contains("is-open"))els.detailBackdrop.hidden=true},220)}
function editPartner(id){state.role="admin";localStorage.setItem("tsf-role",state.role);location.href=`verwaltung.html?edit=${encodeURIComponent(id)}`}
function deletePartner(id){const p=state.partners.find(x=>x.id===id);if(!p||!confirm(`${p.name} wirklich löschen?`))return;state.partners=state.partners.filter(x=>x.id!==id);savePartners();render();showToast(`${p.name} wurde gelöscht.`)}
function fillForm(p){if(!$("#partnerId"))return;$("#partnerId").value=p.id;$("#partnerType").value=p.type;$("#partnerName").value=p.name;$("#contactName").value=p.contactName;$("#contactPhone").value=p.contactPhone;$("#contactEmail").value=p.contactEmail;$("#partnerStudio").value=p.studio;$("#closedBy").value=p.closedBy;$("#lastContact").value=p.lastContact;$("#conditions").value=p.conditions;$("#notes").value=p.notes}
function handleFormSubmit(e){e.preventDefault();if(!isAdmin()||!$("#partnerId"))return showToast("Nur Clubleiter können Partnerdaten speichern.","error");if(!els.partnerForm.checkValidity()){els.formError.hidden=false;els.partnerForm.reportValidity();return}const id=$("#partnerId").value||`p-${Date.now()}`;const p={id,type:$("#partnerType").value,name:$("#partnerName").value.trim(),contactName:$("#contactName").value.trim(),contactPhone:$("#contactPhone").value.trim(),contactEmail:$("#contactEmail").value.trim(),studio:$("#partnerStudio").value,closedBy:$("#closedBy").value.trim(),lastContact:$("#lastContact").value,conditions:$("#conditions").value.trim(),notes:$("#notes").value.trim(),status:"aktiv"};const i=state.partners.findIndex(x=>x.id===id);if(i>=0)state.partners[i]=p;else state.partners.unshift(p);savePartners();resetForm();render();showToast(`${p.name} wurde gespeichert.`)}
function resetForm(){if(!$("#partnerId"))return;els.partnerForm.reset();$("#partnerId").value="";$("#lastContact").value=new Date().toISOString().slice(0,10);els.formError.hidden=true}
function renderVisibility(){els.overviewSections.hidden=state.page!=="uebersicht";els.adminPanel.hidden=state.page!=="verwaltung";if(els.partnerForm)els.partnerForm.querySelectorAll("input,select,textarea,button").forEach(f=>f.disabled=!isAdmin())}
function syncInputs(){els.partnerSearch.value=state.query;els.globalSearch.value=state.query;els.studioFilter.value=state.studio}
function showToast(msg,type="success"){els.toast.textContent=msg;els.toast.style.borderLeftColor=type==="error"?"var(--error)":"var(--success)";els.toast.hidden=false;clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>els.toast.hidden=true,3600)}
function render(){renderHeader();renderNavigation();renderKpis();renderVisibility();renderList();syncInputs()}
function bindEvents(){els.roleToggle.addEventListener("click",()=>{state.role=isAdmin()?"employee":"admin";localStorage.setItem("tsf-role",state.role);render()});els.pagePrimaryAction.addEventListener("click",()=>location.href="verwaltung.html");[els.partnerSearch,els.globalSearch].forEach(i=>i.addEventListener("input",e=>{state.query=e.target.value;syncInputs();renderList()}));els.studioFilter.addEventListener("change",e=>{state.studio=e.target.value;renderList()});els.resetFilters.addEventListener("click",()=>{state.query="";state.studio="alle";render()});els.emptyReset.addEventListener("click",()=>{state.query="";state.studio="alle";render()});if(els.partnerForm)els.partnerForm.addEventListener("submit",handleFormSubmit);if(els.cancelEdit)els.cancelEdit.addEventListener("click",resetForm);els.closeDrawer.addEventListener("click",closeDrawer);els.detailBackdrop.addEventListener("click",closeDrawer);document.querySelectorAll("[data-quick]").forEach(b=>b.addEventListener("click",()=>location.href=b.dataset.quick==="firma"?"firmenfitness.html":b.dataset.quick==="verein"?"vereinsfitness.html":"verwaltung.html"));document.addEventListener("keydown",e=>{if(e.key==="Escape")closeDrawer()})}
bindEvents();resetForm();const editId=new URLSearchParams(location.search).get("edit");if(editId){const p=state.partners.find(x=>x.id===editId);if(p)fillForm(p)}render();
